services:
  # ─────── Backend Service ───────
  - type: web
    name: be-todo
    env: docker
    branch: main                # or whatever branch you’ll push to
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: <YOUR_RENDER_DB_HOST>
      - key: DB_USER
        value: <YOUR_RENDER_DB_USER>
      - key: DB_PASSWORD
        value: <YOUR_RENDER_DB_PASSWORD>
      - key: DB_NAME
        value: todo_db
      - key: PORT
        value: "5000"

  # ─────── Frontend Service ───────
  - type: web
    name: fe-todo
    env: docker
    branch: main
    dockerfilePath: frontend/Dockerfile
    args:                        # build-time args for the React build
      - key: REACT_APP_API_URL
        value: https://be-todo.onrender.com
    envVars:
      - key: PORT
        value: "80"
