pipeline {
  agent any
  tools {
    nodejs 'NodeJS-20.x'
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-creds',
            url: 'https://github.com/pomegranateis/A2.git'
      }
    }

    stage('Install') {
      steps {
        sh 'npm install'
      }
    }

    stage('Build') {
      steps {
        sh 'npm run build'
      }
    }

    stage('Test') {
      steps {
        sh 'npm test'
      }
      post {
        always {
          junit 'junit.xml'
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          docker.build('pomegranatei/node-app:latest')
          docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-creds') {
            docker.image('pomegranatei/node-app:latest').push()
          }
        }
      }
    }
  }
}
